name: Staging Tests

on:
  workflow_dispatch:

jobs:

  staging-group1:
    name: "Group 1 - Calendar (light)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/staging/calendar/stg-blcktime.cy.js,cypress/e2e/staging/calendar/stg-invoices.cy.js,cypress/e2e/staging/calendar/stg-newAppt.cy.js

  staging-group2:
    name: "Group 2 - Calendar (heavy)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/staging/calendar/stg-crtapt.cy.js,cypress/e2e/staging/calendar/stg-newchck.cy.js,cypress/e2e/staging/calendar/stg-apptchck.cy.js

  staging-group3:
    name: "Group 3 - Employees & Customers"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/staging/employees/**/*.cy.js,cypress/e2e/staging/customers/**/*.cy.js

  staging-group4:
    name: "Group 4 - Inventory, Offers, Subs, Coupons & Giftcards"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/staging/inventory/**/*.cy.js,cypress/e2e/staging/offers/**/*.cy.js,cypress/e2e/staging/subscriptions/**/*.cy.js,cypress/e2e/staging/coupons/**/*.cy.js,cypress/e2e/staging/giftcards/**/*.cy.js
